steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/payments:${_VERSION}', '-f', 'Dockerfile', '.']
images: [
  '${_REGISTRY}/$PROJECT_ID/payments:${_VERSION}',
]
